name: Continous Integration

on:
  pull_request:
  push:
    branches:
    - master
    tags: 'v[0-9]+.[0-9]+.[0-9]+'
    paths-ignore:
    - './idea'
    - 'README.md'
    - 'LICENSE'
    - '.github/**'
    - '!.github/workflows/**'

env:
  java: 1.8

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - name: Setup Java
      uses: actions/setup-java@v1
      with:
        java-version: '${{ env.java }}'
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Cache Maven packages
      uses: actions/cache@v2
      with:
        path: ~/.m2
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
        restore-keys: ${{ runner.os }}-m2
    - name: Install Bamboo SDK
      run: |
        wget -q https://marketplace.atlassian.com/download/plugins/atlassian-plugin-sdk-tgz
        mkdir opt
        tar -xzf *plugin-sdk* -C opt
        mv opt/*plugin-sdk* opt/atlassian-plugin-sdk
        chmod a+x opt/atlassian-plugin-sdk/bin/*
        chmod a+x opt/atlassian-plugin-sdk/apache-maven-*/bin/*
        echo "opt/atlassian-plugin-sdk/bin" >> $GITHUB_PATH
        opt/atlassian-plugin-sdk/bin/atlas-version
    - name: Spotless
      run: atlas-mvn -B spotless:check
    - name: Build
      run: atlas-package -DskipTests=true
    - name: Copy artifact
      run: mkdir staging && cp target/*.jar staging
    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: plugin
        path: staging

  test:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Java
        uses: actions/setup-java@v1
        with:
          java-version: '${{ env.java }}'
      - uses: actions/checkout@v2
      - name: Cache Maven packages
        uses: actions/cache@v2
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2
      - name: Install Bamboo SDK
        run: |
          wget -q https://marketplace.atlassian.com/download/plugins/atlassian-plugin-sdk-tgz
          mkdir opt
          tar -xzf *plugin-sdk* -C opt
          mv opt/*plugin-sdk* opt/atlassian-plugin-sdk
          chmod a+x opt/atlassian-plugin-sdk/bin/*
          chmod a+x opt/atlassian-plugin-sdk/apache-maven-*/bin/*
          echo "opt/atlassian-plugin-sdk/bin" >> $GITHUB_PATH
          opt/atlassian-plugin-sdk/bin/atlas-version
      - name: Unit tests
        run: atlas-unit-test
      - name: Integration tests
        run: atlas-integration-test

  prepRelease:
    needs: [build, test]
    if: github.ref == 'refs/heads/master'
    name: Prepare Release
    runs-on: ubuntu-latest
    steps:
    - name: Setup Java
      uses: actions/setup-java@v1
      with:
        java-version: '${{ env.java }}'
    - uses: actions/checkout@v2
    - name: Cache Maven packages
      uses: actions/cache@v2
      with:
        path: ~/.m2
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
        restore-keys: ${{ runner.os }}-m2
    - name: Install Bamboo SDK
      run: |
        wget -q https://marketplace.atlassian.com/download/plugins/atlassian-plugin-sdk-tgz
        mkdir opt
        tar -xzf *plugin-sdk* -C opt
        mv opt/*plugin-sdk* opt/atlassian-plugin-sdk
        chmod a+x opt/atlassian-plugin-sdk/bin/*
        chmod a+x opt/atlassian-plugin-sdk/apache-maven-*/bin/*
        echo "opt/atlassian-plugin-sdk/bin" >> $GITHUB_PATH
        opt/atlassian-plugin-sdk/bin/atlas-version
    - name: Setup Git
      run: |
        git config user.email "actions@github.com"
        git config user.name "GitHub Actions"
    - name: Execute Maven Prepare Release
      run: atlas-mvn -B release:prepare
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  
  release:
    needs: [build, test, prepRelease]
    if: startsWith(github.ref, 'refs/tags/v')
    name: Create Release
    runs-on: ubuntu-latest
    steps:
    - name: Setup Java
      uses: actions/setup-java@v1
      with:
        java-version: '${{ env.java }}'
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Cache Maven packages
      uses: actions/cache@v2
      with:
        path: ~/.m2
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
        restore-keys: ${{ runner.os }}-m2
    - name: Install Bamboo SDK
      run: |
        wget -q https://marketplace.atlassian.com/download/plugins/atlassian-plugin-sdk-tgz
        mkdir opt
        tar -xzf *plugin-sdk* -C opt
        mv opt/*plugin-sdk* opt/atlassian-plugin-sdk
        chmod a+x opt/atlassian-plugin-sdk/bin/*
        chmod a+x opt/atlassian-plugin-sdk/apache-maven-*/bin/*
        echo "opt/atlassian-plugin-sdk/bin" >> $GITHUB_PATH
        opt/atlassian-plugin-sdk/bin/atlas-version
    - name: Build Release
      run: atlas-package -DskipTests=true
    - name: Copy artifact
      run: mkdir staging && cp target/*.jar staging
    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: Release ${{ github.ref }}
        draft: false
        prerelease: false
    - name: Upload Release Asset
      id: upload-release-asset 
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: staging/*.jar
        asset_name: ${{ github.ref }}
        asset_content_type: application/zip