name: Continous Integration

on:
  pull_request:
  push:
    branches:
    - master
    tags: '[0-9]+.[0-9]+.[0-9]+'
    paths-ignore:
    - './idea'
    - 'README.md'
    - 'LICENSE'
    - '.github/**'
    - '!.github/workflows/build.yml'

env:
  java: 1.8
  bambooSetupScript: 'wget -q https://marketplace.atlassian.com/download/plugins/atlassian-plugin-sdk-tgz
    mkdir opt
    tar -xzf *plugin-sdk* -C opt
    mv opt/*plugin-sdk* opt/atlassian-plugin-sdk
    chmod a+x opt/atlassian-plugin-sdk/bin/*
    chmod a+x opt/atlassian-plugin-sdk/apache-maven-*/bin/*
    echo "opt/atlassian-plugin-sdk/bin" >> $GITHUB_PATH
    opt/atlassian-plugin-sdk/bin/atlas-version'

jobs:
  format:
    runs-on: ubuntu-latest
    steps:
    - name: Setup Java
      uses: actions/setup-java@v1
      with:
        java-version: '${{ env.java }}'
    - name: Install Bamboo SDK
      run: |
        wget -q https://marketplace.atlassian.com/download/plugins/atlassian-plugin-sdk-tgz
        mkdir opt
        tar -xzf *plugin-sdk* -C opt
        mv opt/*plugin-sdk* opt/atlassian-plugin-sdk
        chmod a+x opt/atlassian-plugin-sdk/bin/*
        chmod a+x opt/atlassian-plugin-sdk/apache-maven-*/bin/*
        echo "opt/atlassian-plugin-sdk/bin" >> $GITHUB_PATH
        echo "opt/atlassian-plugin-sdk/apache-maven-*/bin" >> $GITHUB_PATH
        opt/atlassian-plugin-sdk/bin/atlas-version
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Cache Maven packages
      uses: actions/cache@v2
      with:
        path: ~/.m2
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
        restore-keys: ${{ runner.os }}-m2
    - name: Spotless
      run: atlas-mvn -B spotless:check

  build:
    runs-on: ubuntu-latest
    steps:
    - name: Setup Java
      uses: actions/setup-java@v1
      with:
        java-version: '${{ env.java }}'
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Cache Maven packages
      uses: actions/cache@v2
      with:
        path: ~/.m2
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
        restore-keys: ${{ runner.os }}-m2
    - name: Install Bamboo SDK
      run: |
        '${{bambooSetupScript}}'
    - name: Build
      run: atlas-package -B -DskipTests=true
    - if: ${{ success() }}
      run: mkdir staging && cp target/*.jar staging
    - name: Upload artifact
      if: ${{ success() }}
      uses: actions/upload-artifact@v2
      with:
        name: plugin
        path: staging

  test:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Java
        uses: actions/setup-java@v1
        with:
          java-version: '${{ env.java }}'
      - name: Install Bamboo SDK
        run: |
          wget -q https://marketplace.atlassian.com/download/plugins/atlassian-plugin-sdk-tgz
          mkdir opt
          tar -xzf *plugin-sdk* -C opt
          mv opt/*plugin-sdk* opt/atlassian-plugin-sdk
          chmod a+x opt/atlassian-plugin-sdk/bin/*
          chmod a+x opt/atlassian-plugin-sdk/apache-maven-*/bin/*
          echo "opt/atlassian-plugin-sdk/bin" >> $GITHUB_PATH
          echo "opt/atlassian-plugin-sdk/apache-maven-*/bin" >> $GITHUB_PATH
          opt/atlassian-plugin-sdk/bin/atlas-version
      - uses: actions/checkout@v2
      - name: Cache Maven packages
        uses: actions/cache@v2
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2
      - name: Unit tests
        run: atlas-mvn -B test
      - name: Integration tests
        run: atlas-mvn -B test


